[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "nodejs_20"]

[phases.install]
cmds = [
  "python3.11 -m ensurepip --upgrade",
  "python3.11 -m pip install --upgrade pip setuptools wheel",
  "cd gateway && python3.11 -m pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd gateway && python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "20"
