[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "nodejs_20"]

[phases.install]
cmds = [
  "python3.11 -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel",
  "cd gateway && /app/.venv/bin/pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd gateway && /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "20"
