[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/gateway"
PORT = "$PORT"

# 서비스별 설정
[deploy.services]
frontend = { path = "frontend", dockerfile = "Dockerfile" }
gateway = { path = "gateway", dockerfile = "Dockerfile" }
auth_service = { path = "service/auth-service", dockerfile = "Dockerfile" }
