[build]
builder = "nixpacks"

[deploy]
startCommand = "cd gateway && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"

# 서비스별 설정
[deploy.services]
frontend = { path = "frontend", buildCommand = "npm install && npm run build", startCommand = "npm start" }
gateway = { path = "gateway", buildCommand = "pip install -r requirements.txt", startCommand = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT" }
auth_service = { path = "service/auth-service", buildCommand = "pip install -r requirements.txt", startCommand = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT" }
