# Railway 설정 - Gateway 서비스 배포
[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/gateway"
PORT = "$PORT"
